export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const MARK_TASK = 'MARK_TASK';
export const REMOVE_COMPLETED_TASKS = 'REMOVE_COMPLETED_TASKS';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';

export const SET_FILTER = 'SET_FILTER';
